config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/home')
  get 'home' , to: 'pages#home', as: 'home'
  post 'home', to: 'pages#create'
  get 'home/new', to: 'pages#new', as:'new'

  #Left menu Bar
  get 'home/myprofile', to: 'pages#myprofile', as: 'myprofile'
  get 'home/mypost', to: 'pages#mypost', as: 'mypost'
  get 'home/myevent', to: 'pages#myevent', as: 'myevent'

  delete 'home/:id', to: 'pages#delete', as: 'delete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @posts = Post.all
        render :home
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(params.require(:post).permit(:title, :description))
        if @post.save
            flash[:success] = "New Post successfully created"
            redirect_to home_url
        else
            flash[:error] = "New Post creation failed"
            render :new
        end
    end

    def delete
        @p = Post.find(params[:id])
        @p.destroy
        flash[:success]= "Post is Successfully deleted"
        redirect_to home_url
    end

   
#Left Menu Bar
    def myprofile
        render :myprofile
    end

    def mypost
        @posts = Post.all
        render :mypost
    end

    def myevent
        render :myevent
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        bootstrap_alert_class = {
          'success' => 'alert-success',
          'error'   => 'alert-danger',
          'notice'  => 'alert-info',
          'alert'   => 'alert-danger',
          'warn'    => 'alert-warning'
        }
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoGitProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <main>
     <% flash.each do |key, message| %>
    <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
       <div class="text-center alert-message"><%= message %></div>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
     <div class="top-nav" role="navigation">
        <%= link_to 'Home Icon', home_path %>
        <%= link_to 'Group Icon', home_path %>
     </div>
     <nav class="lmb">
      <%= link_to 'My Profile', myprofile_path %>
      <%= link_to 'My Posts', mypost_path %>
     <%= link_to 'My Events', myevent_path %>   
     </nav>
       <%= yield %>
    </main> 
     </body>
</html>

app/views/pages/home.html.erb
<div class="myDiv">
    <div class="heading-text">
        <h1>Facebook home Page</h1>
    </div>

    <div class="heading-text"> <%= link_to 'Create New Post', new_path %></div>

    <div class="pdiv">
        <% @posts.each do |p|%>
             <p><%=p.title%></p>
             <p class="pl"><%=p.description%></p>
             <%= button_to "Delete", delete_path(p), method: :delete, data:{turbo: false}%> 
        <% end%>
    </div>
<div>

app/views/pages/myevent.html.erb
<div class="myDiv">
    <h1>This will show current user events</h1>
</div>

app/views/pages/mypost.html.erb
<div class="myDiv">
    <div class="pdiv">
        <% @posts.each do |p|%>
             <p><%=p.title%></p>
            <p class="pl"><%=p.description%></p>
        <% end%>
    </div>
</div>

app/views/pages/myprofile.html.erb
<h1> This will display Current User Profile (We need to create a Model class for User) </h1>

app/views/pages/new.html.erb
<div class="heading-text">
    <h1>Create new post</h1>
</div >
<div class="pdiv">
<%= bootstrap_form_with model: @post, url: home_path, method: :post, data: { turbo: false } do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

<%= link_to 'Cancel', home_path %>
</div>